name: coba
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_logger: ^4.0.8+8
  dropdown_button2: ^1.9.2
  easy_mask: ^2.0.1
  flutter:
    sdk: flutter
  flutter_jailbreak_detection: ^1.8.0
  flutter_screenutil: 5.6.0
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.1.1
  get: 4.6.5
  get_storage: ^2.0.3
  google_fonts: 3.0.1
  hive: ^2.2.3
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  shimmer: ^2.0.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
       - asset: assets/fonts/CustomIcons.ttf
