/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
// ignore_for_file: constant_identifier_names, unused_field, use_late_for_private_fields_and_variables

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_left = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrow_right = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData bookmark = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData clock = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData edit = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData location = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData minus_border = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData more = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData more_1 = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData play = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData plus = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData plus_border = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData profile = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData recipe = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData star = IconData(0xe80f, fontFamily: _kFontFam);
}
